cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: abc
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def
    yashs:
      email: yash.sharma.now@gmail.com
      name: Yash Sharma
      password: $2b$12$x1SehpcRhnthLGlRloDf/OPJVP1XaYci7iynbVI1wi1Lz1wwaQ1ea
preauthorized:
  emails:
  - yash.sharma.now@gmail.com
